package com.example.realestate.dto;

import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
public class RealEstateCsvRecord {
//    private String id;
    private String mlsNumber;
    private String taxId;
    private String address;
    private String city;
    private String state;
    private String zip;
    private String status;
    private String shortSale;
    private String timeUC;
    private Integer dom;
    private LocalDate soldDate;
    private String soldTerms;
    private String soldPrice;
    private String soldConcessions;
    private String listPrice;
    private String originalListPrice;
    private LocalDate underContractDate;
    private LocalDate entryDate;
    private LocalDate effectiveDateOfListingAgreement;
    private LocalDate statusChangeDate;
    private LocalDate offMarketDate;
    private LocalDate reinstatedDate;
    private LocalDate cancelDate;
    private String offerUnder3rdPartyReview;
    private LocalDate priceIncreaseDate;
    private Integer priceIncreaseDaysBack;
    private LocalDate priceReductionDate;
    private Integer priceReductionDaysBack;
    private LocalDate backupStatusDate;
    private LocalDate withdrawalDate;
    private LocalDate expireDate;
    private BigDecimal acres;
    private String propertyType;
    private String style;
    private Integer yearBuilt;
    private Integer grossLivingAreaGla;
    private Integer totalSquareFeet;
    private Integer totalBedrooms;
    private Integer totalBathrooms;
    private Integer totalFullBathrooms;
    private Integer totalThreeQuarterBathrooms;
    private Integer totalHalfBathrooms;
    private Integer totalKitchens;
    private Integer basementSquareFeet;
    private Boolean basementFinished;
    private Integer basementBedrooms;
    private Integer basementFullBathrooms;
    private Integer basementThreeQuarterBathrooms;
    private Integer basementHalfBathrooms;
    private String basement;
    private String heating;
    private String airConditioning;
    private Integer garageCapacity;
    private Integer carportCapacity;
    private String garageParking;
    private Integer decks;
    private Boolean solar;
    private String solarOwnership;
    private Integer totalFireplaces;
    private String landscape;
    private Boolean poolAvailable;
    private String poolDetails;
    private String hoaFee;
    private String hoaAmenities;
    private String hoaRemarks;
    private Integer mainFloorSquareFeet;
    private Integer secondFloorSquareFeet;
    private Integer thirdFloorSquareFeet;
    private Integer fourthFloorSquareFeet;
    private String exteriorFeatures;
    private String floor;
    private String county;
    private String interiorFeatures;
    private String publicRemarks;
    private String bacCompensation;
    private String mlsLink;
    private String quality;
    private String condition;
    private String locationPositive;
    private String locationNegative;
    private String viewPositive;
    private String viewNegative;
    private Boolean adu;
    private Boolean remodUpdate;
    private Boolean outbuilding;
    private String fullAddress;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private String legal;
    private Boolean verified;
    private Integer daysBack;
    private Boolean legalMatchToTax;
    private String countyRecordLink;
    private String htmlBodyTd;
}
